server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cart
    username: postgres
    password: KuzPsina
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  redis:
    host: localhost
    port: 6379

  cache:
    cache-names:
      - Cart
    redis:
      key-prefix: test

